-- Limpar tabela e reiniciar IDs
TRUNCATE public.cursos RESTART IDENTITY;

-- Inserir todos os cursos
INSERT INTO public.cursos (title, category, duration, modality) VALUES
-- Bacharelado
('Administração', 'Bacharelado', '4 anos', 'Digital'),
('Administração Pública', 'Bacharelado', '4 anos', 'Digital'),
('Agronomia', 'Bacharelado', '5 anos', 'Semipresencial'),
('Arquitetura e Urbanismo', 'Bacharelado', '5 anos', 'Semipresencial'),
('Biomedicina', 'Bacharelado', '4 anos', 'Semipresencial'),
('Ciência da Computação', 'Bacharelado', '4 anos', 'Digital'),
('Ciência Política', 'Bacharelado', '4 anos', 'Digital'),
('Ciências Biológicas', 'Bacharelado', '4 anos', 'Semipresencial'),
('Ciências Contábeis', 'Bacharelado', '4 anos', 'Digital'),
('Ciências Econômicas', 'Bacharelado', '4 anos', 'Digital'),
('Engenharia Ambiental', 'Bacharelado', '5 anos', 'Semipresencial'),
('Engenharia Civil', 'Bacharelado', '5 anos', 'Semipresencial'),
('Engenharia de Computação', 'Bacharelado', '5 anos', 'Semipresencial'),
('Engenharia de Produção', 'Bacharelado', '5 anos', 'Semipresencial'),
('Engenharia de Software', 'Bacharelado', '4 anos', 'Digital'),
('Engenharia Elétrica', 'Bacharelado', '5 anos', 'Semipresencial'),
('Engenharia Mecânica', 'Bacharelado', '5 anos', 'Semipresencial'),
('Engenharia Mecatrônica', 'Bacharelado', '5 anos', 'Semipresencial'),
('Estudos Teóricos Psicanalíticos e Sociais', 'Bacharelado', '4 anos', 'Digital'),
('Farmácia', 'Bacharelado', '5 anos', 'Semipresencial'),
('Filosofia', 'Bacharelado', '4 anos', 'Digital'),
('Física', 'Bacharelado', '4 anos', 'Semipresencial'),
('Fisioterapia', 'Bacharelado', '4 anos', 'Semipresencial'),
('Fonoaudiologia', 'Bacharelado', '4 anos', 'Semipresencial'),
('Geografia', 'Bacharelado', '4 anos', 'Digital'),
('História', 'Bacharelado', '4 anos', 'Digital'),
('Interdisciplinar em Humanidades', 'Bacharelado', '4 anos', 'Digital'),
('Jornalismo', 'Bacharelado', '4 anos', 'Digital'),
('Matemática', 'Bacharelado', '4 anos', 'Semipresencial'),
('Naturologia', 'Bacharelado', '4 anos', 'Semipresencial'),
('Nutrição', 'Bacharelado', '4 anos', 'Semipresencial'),
('Óptica e Optometria', 'Bacharelado', '4 anos', 'Semipresencial'),
('Psicopedagogia', 'Bacharelado', '4 anos', 'Semipresencial'),
('Publicidade e Propaganda', 'Bacharelado', '4 anos', 'Digital'),
('Química', 'Bacharelado', '4 anos', 'Semipresencial'),
('Relações Internacionais', 'Bacharelado', '4 anos', 'Digital'),
('Relações Públicas', 'Bacharelado', '4 anos', 'Digital'),
('Serviço Social', 'Bacharelado', '4 anos', 'Semipresencial'),
('Sistemas de Informação', 'Bacharelado', '4 anos', 'Digital'),
('Teologia', 'Bacharelado', '4 anos', 'Digital'),
('Terapia Ocupacional', 'Bacharelado', '4 anos', 'Semipresencial'),
('Zootecnia', 'Bacharelado', '5 anos', 'Semipresencial'),

-- Bacharelado 2.0
('Administração 2.0', 'Bacharelado 2.0', '2 anos', 'Digital'),
('Ciências Contábeis 2.0', 'Bacharelado 2.0', '2 anos', 'Digital'),
('Ciências Econômicas 2.0', 'Bacharelado 2.0', '2 anos', 'Digital'),
('Educação Física 2.0', 'Bacharelado 2.0', '2 anos', 'Semipresencial'),
('Engenharia Ambiental 2.0', 'Bacharelado 2.0', '2 anos', 'Semipresencial'),
('Engenharia de Produção 2.0', 'Bacharelado 2.0', '2 anos', 'Semipresencial'),

-- Licenciatura
('Artes Visuais', 'Licenciatura', '4 anos', 'Semipresencial'),
('Ciências Biológicas', 'Licenciatura', '4 anos', 'Semipresencial'),
('Ciências Sociais', 'Licenciatura', '4 anos', 'Semipresencial'),
('Educação Especial', 'Licenciatura', '4 anos', 'Semipresencial'),
('Filosofia', 'Licenciatura', '4 anos', 'Semipresencial'),
('Física', 'Licenciatura', '4 anos', 'Semipresencial'),
('Formação Pedagógica - Biologia', 'Licenciatura', '4 anos', 'Semipresencial'),
('Formação Pedagógica - Filosofia', 'Licenciatura', '4 anos', 'Semipresencial'),
('Formação Pedagógica - Geografia', 'Licenciatura', '4 anos', 'Semipresencial'),
('Formação Pedagógica - História', 'Licenciatura', '4 anos', 'Semipresencial'),
('Formação Pedagógica - Letras Port. e Ing.', 'Licenciatura', '4 anos', 'Semipresencial'),
('Geografia', 'Licenciatura', '4 anos', 'Semipresencial'),
('História', 'Licenciatura', '4 anos', 'Semipresencial'),
('Letras - Libras', 'Licenciatura', '4 anos', 'Semipresencial'),
('Letras - Português e Espanhol', 'Licenciatura', '4 anos', 'Semipresencial'),
('Letras - Português e Inglês', 'Licenciatura', '4 anos', 'Semipresencial'),
('Letras - Português e Japonês', 'Licenciatura', '4 anos', 'Semipresencial'),
('Matemática', 'Licenciatura', '4 anos', 'Semipresencial'),
('Pedagogia', 'Licenciatura', '4 anos', 'Semipresencial'),
('Química', 'Licenciatura', '4 anos', 'Semipresencial'),

-- Licenciatura 2.0
('Ciências Biológicas - Licenciados', 'Licenciatura 2.0', '1.5 anos', 'Semipresencial'),
('Ciências Sociais - Licenciados', 'Licenciatura 2.0', '1.5 anos', 'Semipresencial'),
('Filosofia - Licenciados', 'Licenciatura 2.0', '1.5 anos', 'Semipresencial'),
('Geografia - Licenciados', 'Licenciatura 2.0', '1.5 anos', 'Semipresencial'),
('História - Licenciados', 'Licenciatura 2.0', '1.5 anos', 'Semipresencial'),
('Letras Português e Inglês - Licenciados', 'Licenciatura 2.0', '1.5 anos', 'Semipresencial'),

-- Bach/Licen
('Educação Física (Área Básica de Ingresso)', 'Bach/Licen', '4 anos', 'Semipresencial'),

-- Tecnólogo
('CST em Análise de Dados de Alta Performance', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Análise e Desenvolvimento de Sistemas', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Banco de Dados', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Cibersegurança', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Ciência de Dados', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Coaching e Mentoring', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Coding', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Comércio Exterior', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Computação em Nuvem', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Conciliação, Mediação e Arbitragem', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Criminologia', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Desenvolvimento Back-End', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Desenvolvimento Full Stack', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Desenvolvimento Mobile', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Design de Animação', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Design de Experiência', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Design de Interiores', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Design de Moda', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Design de Produto', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Design Gráfico', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Empreendedorismo', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Estética e Cosmética', 'Tecnólogo', '2.5 anos', 'Semipresencial'),
('CST em Eventos', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Fotografia', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gastronomia', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gerontologia', 'Tecnólogo', '2 anos', 'Semipresencial'),
('CST em Gestão Ambiental', 'Tecnólogo', '2 anos', 'Semipresencial'),
('CST em Gestão Comercial', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão da Produção Industrial', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão da Qualidade', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão da Saúde Pública', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão da Tecnologia da Informação', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Gestão das Organizações do Terceiro Setor', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão de Cooperativas', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão de Negócios Imobiliários', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão de Recursos Humanos', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão de Segurança Privada', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão de Turismo', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão Desportiva e de Lazer', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão do Agronegócio', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão Financeira', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Gestão Hospitalar', 'Tecnólogo', '2.5 anos', 'Semipresencial'),
('CST em Gestão Pública', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Influenciador Digital', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Inteligência Artificial', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Internet das Coisas', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Jogos Digitais', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Logística', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Marketing', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Marketing Digital', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Perícia Judicial e Extrajudicial', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Podologia', 'Tecnólogo', '2.5 anos', 'Semipresencial'),
('CST em Processos Gerenciais', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Produção Audiovisual', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Produção Cultural', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Produção Midiática', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Radiologia', 'Tecnólogo', '2.5 anos', 'Semipresencial'),
('CST em Redes de Computadores', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Secretariado', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Segurança da Informação', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Segurança no Trabalho', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Segurança no Trânsito', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Segurança Pública', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Serviços Jurídicos e Notariais', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Serviços Penais', 'Tecnólogo', '2 anos', 'Digital'),
('CST em Sistemas para Internet', 'Tecnólogo', '2.5 anos', 'Digital'),
('CST em Terapias Integrativas e Complementares', 'Tecnólogo', '2.5 anos', 'Semipresencial');
