-- =============================================
-- Setup completo da tabela public.leads
-- para o formulário com campo cidade
-- LP-Unicsul-2026.1
-- =============================================

CREATE TABLE IF NOT EXISTS public.leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT,
  whatsapp TEXT,
  cidade TEXT,
  curso TEXT,
  indicacao TEXT,
  amigo_nome TEXT,
  amigo_whatsapp TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS nome TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS whatsapp TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS cidade TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS curso TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS indicacao TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS amigo_nome TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS amigo_whatsapp TEXT;
ALTER TABLE public.leads ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

UPDATE public.leads
SET created_at = now()
WHERE created_at IS NULL;

ALTER TABLE public.leads ALTER COLUMN created_at SET DEFAULT now();

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_insert_leads" ON public.leads;
CREATE POLICY "anon_insert_leads"
  ON public.leads
  FOR INSERT
  TO anon
  WITH CHECK (true);

DROP POLICY IF EXISTS "authenticated_insert_leads" ON public.leads;
CREATE POLICY "authenticated_insert_leads"
  ON public.leads
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT INSERT ON public.leads TO anon, authenticated;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class
    WHERE relkind = 'S'
      AND relname = 'leads_id_seq'
  ) THEN
    EXECUTE 'GRANT USAGE, SELECT ON SEQUENCE public.leads_id_seq TO anon, authenticated';
  END IF;
END $$;

-- Verificação rápida:
-- SELECT column_name
-- FROM information_schema.columns
-- WHERE table_schema = 'public' AND table_name = 'leads'
-- ORDER BY ordinal_position;
--
-- SELECT policyname, cmd, roles
-- FROM pg_policies
-- WHERE schemaname = 'public' AND tablename = 'leads';
